### ISSUE TITLE
Cannot find module 'mqttws31'

### ISSUE THREAD

**Issue by pdashford** [icanos/ng2-mqtt#3]
I have installed the package using nom and is in my packages.json, however when trying to import this in angular2 i get an error stating it cannot find the module. I have sourceMapping set to true. Could you perhaps provide more information on how to get this up and running, does there need to be any additional scripts adding to index.html? Thanks in advance.

**Comment by icanos** [comment]
You need to include the mqttws31.js script in your index.html file.

<script type="text/javascript" src="/path/to/mqttws31.js"></script>

Hope it helps!

**Comment by riccardodegan-geekcups** [comment]
I have use:

```
import {Paho} from 'ng2-mqtt/mqttws31';
``` 

instead of:

```
import {Paho} from 'mqttws31';
```

and it work!
