### ISSUE TITLE
Secure connection

### ISSUE THREAD

**Issue by AinoL** [icanos/ng2-mqtt#5]
Hello!

I wonder if it's at all possible to create a wss connection instead of ws by using this library? I've been trying to modify the js file to use a secure connection but I keep getting 403 errors.

Thanks!

**Comment by icanos** [comment]
I think you could do it by providing a connectOptions object to the connect function setting useSSL to true.

Example:
this._client.connect({ onSuccess: this.onConnected.bind(this); **useSSL: true;** });

Reference:
http://www.eclipse.org/paho/files/jsdoc/symbols/Paho.MQTT.Client.html

Hope it helps!

**Comment by AinoL** [comment]
Actually that and tweaks to my client params did the trick. Closing issue.
