### ISSUE TITLE
connection problems

### ISSUE THREAD

**Issue by liquidpizza** [icanos/ng2-mqtt#9]
I wrote a little demo app with this lib but I am not able to connect to the server.

The browser claims it is not able to connect to `ws://192.168.100.103:1883/`.

None of the success messages is shown in the console either.

**Comment by liquidpizza** [comment]
this problem was not the lib, but my broker. i know use [this](https://github.com/mcollina/mosca/wiki/MQTT-over-Websockets)

**Comment by thachhuynh95** [comment]
I have the same problem, can u explain more clearly ?

**Comment by liquidpizza** [comment]
If I remember it correctly the broker I used (probably mosquitto) did not support websockets. So my angular app could not connect.

Using mosca fixed this issue.
